catalog/urls.py
from django.urls import path
from . import views
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import RegisterDoneView
from .views import RegisterUserView

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),

]

design/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    first_name = models.CharField(max_length=100, blank=True, verbose_name='Имя')
    patronymic = models.CharField(max_length=100, blank=True, verbose_name='Отчество')
    last_name = models.CharField(max_length=100, blank=True, verbose_name='Фамилия')

    class Meta(AbstractUser.Meta):
        pass

catalog/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import AdvUser
from django.core.validators import RegexValidator

class ChangeUserInfoForm(forms.ModelForm):
   email = forms.EmailField(required=True, label='Адрес электронной почты')

   class Meta:
       model = AdvUser
       fields = ('username', 'email', 'first_name', 'patronymic', 'last_name')

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты', validators=[
        RegexValidator(
            regex=r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$',
            message=' Необходим валидный формат email-адреса'
        )
    ])

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,

    )
    password2 = forms.CharField(
        label='Пароль (повторно)',
        widget=forms.PasswordInput,help_text='Повторите тот же самый пароль еще раз'
    )
    first_name = forms.CharField(label='Имя', max_length=100, validators=[
        RegexValidator(
            regex=r'^[а-яА-ЯёЁ\s-]+$',
            message='Имя должно состоять только из кириллических букв, пробелов и дефисов.'
        )
    ])
    last_name = forms.CharField(label='Фамилия', max_length=100, validators=[
        RegexValidator(
            regex=r'^[а-яА-ЯёЁ-]+$',
            message='Фамилия должно состоять только из кириллических букв и дефисов.'
        )
    ])
    username = forms.CharField(label='Логин', max_length=30, validators=[
        RegexValidator(
            regex=r'^[a-zA-Z-]+$',
            message='Логин должен состоять только из латинских букв и дефисов.'
        )
    ])
    patronymic = forms.CharField(label='Отчество', max_length=100, validators=[
        RegexValidator(
            regex=r'^[а-яА-ЯёЁ-]+$',
            message='Отчество должно состоять только из кириллических букв и дефисов.'
        )
    ])
    consent = forms.BooleanField(label='Согласие на обработку персональных данных')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            self.add_error('password2', ValidationError(
                'Введенные пароли не совпадают.'
            ))


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'first_name', 'patronymic', 'last_name', 'email', 'password1', 'password2', 'consent')

catalog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import AdvUser
from django.views.generic import CreateView
from .forms import RegisterUserForm
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.views.generic.base import TemplateView
from django.contrib.auth import login

def index(request):
    return render(request, 'index.html')


class BBLoginView(LoginView):
    template_name = 'registration/login.html'


@login_required
def profile(request):
    return render(request, 'registration/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'registration/logout.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('catalog:register_done')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object
        tariff = form.cleaned_data.get('tariff')

        subject = 'Регистрация на сайте'
        message = f'Спасибо за регистрацию! '
        from_email = 'malenkoer@mail.ru'
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list)

        try:
            send_mail(subject, message, from_email, recipient_list)
        except Exception as e:
            print(f'Email sending failed: {e}')

        login(self.request, user)
        return response

class RegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'

catalog/templates/index.html
{% load static %} {% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %} {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %}</title>
</head>
<body style="background-color: 	#FFFFFF">
<div class="container-fluid">
    <div  style="" class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3 border-bottom box-shadow">
        <h1 class="mr-md-auto p-2">Design.pro</h1>
        {% if user.is_authenticated %}
        <form class="p-2 text-dark" action="{% url 'catalog:profile' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Профиль</button>
        </form>
        <form class="p-2 text-dark" action="{% url 'catalog:logout'%}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Выйти</button>
        </form>
        {% else %}
        <form class="p-2 text-dark" action="{% url 'catalog:register' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Регистрация</button>
        </form>
        <form class="p-2 text-dark" action="{% url 'catalog:login' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Вход</button>
        </form>
        {% endif %}
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column" style="margin: 15px;">
            <a style="color: black;" class="nav-link root" href="{% url 'catalog:index' %}">Главная</a>
        </nav>
        <div class="container"> {% bootstrap_messages %} {% block content %} {% endblock %}</div>
    </div>
</div>
</body>
</html>